logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
spring:
  redis:
    host: 192.168.1.207
    port: 32769
zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:
